- name: Enable Epel
  yum: name={{ epel_url }} state=present

- name: Install Redis
  yum: name={{ item }} state=installed
  with_items:
   - redis

- name: Copy Redis config
  template: src=redis.j2 dest=/etc/redis.conf owner=root group=root mode=0644
  notify:
   - restart redis

