---
- name: install python setup tools
  yum: name=python-setuptools state=installed
  tags: supervisord

- name: install supervisor with easy_install
  shell: easy_install supervisor
  tags: supervisord

- name: configure supervisord
  shell: /usr/bin/echo_supervisord_conf > {{supervisor.config.file}}
  tags: supervisord

- name: backup default configuration
  shell: cp {{supervisor.config.file}} {{supervisor.config.default}} creates={{supervisor.config.default}}
  tags: supervisord

- name: prepare necessary directories
  file: path={{item}} state=directory recurse=yes
  with_items:
    - "{{supervisor.log.dir}}"
    - "{{supervisor.config.dir}}"
    - "{{supervisor.runtime.dir}}"
  tags: supervisord

- name: configure runtime and log
  ini_file: dest={{supervisor.config.file}}
            section={{item.section}}
            option={{item.option}}
            value={{item.value}}
  with_items:
      - { section: unix_http_server, option: file, value: "{{supervisor.runtime.dir}}/{{supervisor.runtime.socket}}" }
      - { section: supervisorctl, option: serverurl, value: "unix://{{supervisor.runtime.dir}}/{{supervisor.runtime.socket}}" }
      - { section: supervisord, option: pidfile, value: "{{supervisor.runtime.dir}}/{{supervisor.runtime.pidfile}}" }
      - { section: supervisord, option: nodaemon, value: "{{supervisor.runtime.nodaemon}}" }
      - { section: supervisord, option: logfile, value: "{{supervisor.log.dir}}/{{supervisor.log.file}}" }
      - { section: supervisord, option: loglevel, value: "{{supervisor.log.level}}" }
  tags: supervisor

- name: tell supervisor to include relative configurations directory
  ini_file: dest={{supervisor.config.file}}
            section=include
            option=files
            value={{supervisor.config.dir}}/*.conf
            state=present
  notify:
  - start supervisord
  tags: supervisord